version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: wallet_transaction
      POSTGRES_USER: easy_pay
      POSTGRES_PASSWORD: n^76bw!q55t^QM3mUrqf
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  rabbitmq-data:
  postgres-data:
